FROM python:3.10

# Install os dependencies
RUN apt-get update && apt-get install -y vim # <-- here

# Copy only the requirements.txt file
COPY requirements.txt requirements.txt

# Install Python dependencies
RUN pip install -r requirements.txt

# Set the working directory
WORKDIR /app

# Copy all project files
COPY . .

# Expose the application port
EXPOSE 8000

# Run the Django application
CMD ["gunicorn", "myproject.wsgi:application", "--bind", "0.0.0.0:8000"]
